In [1]:
import numpy as np
#陣列運算
a = np.array([1, 3, 5, 7, 9])
a *= 10
a

array([10, 30, 50, 70, 90])

In [2]:
a = np.array([1, 3, 5, 7, 9])
b = np.array([2, 4 , 6, 8, 10])

#陣列運算
a + b

array([ 3,  7, 11, 15, 19])

In [4]:
#2維ndarray

arr = np.array([[1, 3, 5],[2, 4, 6]])
arr.ndim    # 陣列的維度數 (這裡會是 2)
arr.shape   # 陣列的形狀(大小)，回傳 (2, 3)，代表2列3欄
arr.size    # 陣列中元素的總數，這裡是 6
arr.dtype   # 陣列中元素的資料型別，這裡預設會是 int64（或 int32，依環境而定）


dtype('int64')

In [5]:
np.random.rand()
np.random.rand(10, 4)

array([[0.24681984, 0.49782912, 0.37743284, 0.14442534],
       [0.23387653, 0.73869036, 0.02279771, 0.87985668],
       [0.81540632, 0.94940477, 0.41358499, 0.72069859],
       [0.83530871, 0.16555431, 0.76675094, 0.26911689],
       [0.4602335 , 0.07070922, 0.1981969 , 0.81942538],
       [0.81607747, 0.6127727 , 0.50099359, 0.92493329],
       [0.36709755, 0.90540748, 0.47682253, 0.49414514],
       [0.86975463, 0.03590024, 0.91791187, 0.48823042],
       [0.19723214, 0.14627969, 0.24195934, 0.24459246],
       [0.25540205, 0.29270733, 0.94646568, 0.38479362]])

In [16]:
scores = np.random.randint(50, 101,size=(10,5))
scores

array([[55, 80, 55, 62, 85],
       [96, 51, 56, 82, 67],
       [62, 91, 86, 64, 71],
       [64, 92, 60, 78, 50],
       [76, 89, 67, 73, 98],
       [81, 66, 72, 56, 82],
       [69, 77, 58, 50, 80],
       [77, 51, 63, 92, 95],
       [70, 92, 53, 71, 72],
       [59, 90, 71, 73, 92]], dtype=int32)