In [1]:
import numpy as np
arr = np.arange(10) * 10
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [7]:
#索引
arr[1]

#slice
arr[:6] #前6個
arr[-3:] #最後3個

array([70, 80, 90])

In [13]:
scores = np.random.randint(50,101, size=(50, 5))
scores

array([[ 57,  52,  58,  87,  71],
       [ 94,  99,  63,  71,  79],
       [ 63,  64,  98,  83,  72],
       [ 84,  97,  65,  66,  50],
       [ 75,  64,  56,  80,  78],
       [ 52,  63,  57,  91,  83],
       [ 95,  78,  87,  65,  74],
       [ 87,  82,  67,  95,  78],
       [ 99,  72,  95,  53,  87],
       [ 51,  74,  51,  89,  77],
       [ 86,  79,  83,  77,  74],
       [ 82,  99,  53,  60, 100],
       [ 76,  51,  89,  66,  89],
       [ 93,  50,  88,  83,  83],
       [ 64,  78,  96,  83,  95],
       [ 91,  61,  86,  87,  50],
       [ 71,  58,  53,  96,  51],
       [ 83,  83,  76,  63,  99],
       [ 97,  69,  89,  84,  94],
       [ 98,  64,  50,  83,  81],
       [ 88,  85,  71,  95,  67],
       [ 65,  68,  92,  58,  96],
       [ 92,  85,  52,  73,  69],
       [ 60,  62,  74,  99,  89],
       [ 72,  66,  74,  74,  72],
       [ 64,  93,  75,  83,  58],
       [ 83,  87,  81,  93,  58],
       [ 93,  95,  59,  53,  98],
       [ 79,  54,  98,  80,  57],
       [ 98,  

In [14]:
#第一位學生的分數
scores[0] #(5,)
scores[0,:] #(5,)
scores[0:1,:] #(1, 5)

array([[57, 52, 58, 87, 71]], dtype=int32)

In [15]:
#前5位學生
scores[:5]
#前5位學生,前3個分數
scores[:5,:3]

array([[57, 52, 58],
       [94, 99, 63],
       [63, 64, 98],
       [84, 97, 65],
       [75, 64, 56]], dtype=int32)

In [16]:
#第1科分數
scores[:,0]
scores[:,1]
scores[:,2]

array([58, 63, 98, 65, 56, 57, 87, 67, 95, 51, 83, 53, 89, 88, 96, 86, 53,
       76, 89, 50, 71, 92, 52, 74, 74, 75, 81, 59, 98, 88, 69, 52, 84, 52,
       85, 80, 86, 64, 61, 63, 54, 50, 98, 72, 91, 82, 99, 97, 80, 78],
      dtype=int32)

In [17]:
#ndarray可以陣列運算
total = scores[:,0] + scores[:,1] + scores[:,2] + scores[:,3] + scores[:,4]
total

array([325, 406, 380, 362, 353, 346, 399, 409, 406, 342, 399, 394, 371,
       397, 416, 375, 329, 404, 433, 376, 406, 379, 371, 384, 358, 373,
       402, 398, 368, 429, 356, 388, 383, 407, 418, 389, 389, 362, 405,
       365, 365, 345, 394, 375, 403, 361, 467, 330, 349, 389], dtype=int32)

In [18]:
total / 5

array([65. , 81.2, 76. , 72.4, 70.6, 69.2, 79.8, 81.8, 81.2, 68.4, 79.8,
       78.8, 74.2, 79.4, 83.2, 75. , 65.8, 80.8, 86.6, 75.2, 81.2, 75.8,
       74.2, 76.8, 71.6, 74.6, 80.4, 79.6, 73.6, 85.8, 71.2, 77.6, 76.6,
       81.4, 83.6, 77.8, 77.8, 72.4, 81. , 73. , 73. , 69. , 78.8, 75. ,
       80.6, 72.2, 93.4, 66. , 69.8, 77.8])

In [19]:
#np內的function
np.sum(scores,axis=1)
np.mean(scores,axis=1)

array([65. , 81.2, 76. , 72.4, 70.6, 69.2, 79.8, 81.8, 81.2, 68.4, 79.8,
       78.8, 74.2, 79.4, 83.2, 75. , 65.8, 80.8, 86.6, 75.2, 81.2, 75.8,
       74.2, 76.8, 71.6, 74.6, 80.4, 79.6, 73.6, 85.8, 71.2, 77.6, 76.6,
       81.4, 83.6, 77.8, 77.8, 72.4, 81. , 73. , 73. , 69. , 78.8, 75. ,
       80.6, 72.2, 93.4, 66. , 69.8, 77.8])

In [20]:
#實體方法
scores.sum(axis=1)
scores.mean(axis=1)

array([65. , 81.2, 76. , 72.4, 70.6, 69.2, 79.8, 81.8, 81.2, 68.4, 79.8,
       78.8, 74.2, 79.4, 83.2, 75. , 65.8, 80.8, 86.6, 75.2, 81.2, 75.8,
       74.2, 76.8, 71.6, 74.6, 80.4, 79.6, 73.6, 85.8, 71.2, 77.6, 76.6,
       81.4, 83.6, 77.8, 77.8, 72.4, 81. , 73. , 73. , 69. , 78.8, 75. ,
       80.6, 72.2, 93.4, 66. , 69.8, 77.8])